### ISSUE TITLE
video and audio formats load in 3 seconds (long) (you can reduce this time)

### ISSUE THREAD

**Issue by Wjxfi** [deniscerri/ytdlnis#142]

**Comment by deniscerri** [comment]
You are most likely using yt-dlp as source for formats. If your links are from youtube, choose the other option.
Go to settings  / updating / formats source.

Ytdlp is always slow, theres nothing i can do

**Comment by matt873** [comment]
Is it possible to add an option for omitting certain formats or codecs from the download card for faster loading of info (so yt-dlp doesn't have to fetch these formats or codecs)? For instance, leaving only MP4 and removing WEBM and 3GP or omitting certain codecs, i.e.,  VP9 and AV1, leaving H.264 only to be fetched in the download card?

**Comment by deniscerri** [comment]
The problem is not loading formats. Because that is almost instant. The problem is initiating the ytdlp command. That's what is slow and i can't do anything about it. Even if i make a simple command like  in terminal, it will take almost the same time.

**Comment by matt873** [comment]
I get what you're saying. However, the download card is overburdened with formats and codecs. Is it simple to add a setting to retrieve only specific formats or codecs? It will make the download card cleaner for those who don't need to get info about too many formats.

**Comment by deniscerri** [comment]
I don't believe there is a ytdlp command that lets you retrieve a group of specific formats. It just drops you all of them. Since im getting all of them and later ill filter them to a certain setting, it would take more time than if i were to just show all of them to begin with.

Also there's no point at limiting people's choices. If they are overwhelmed with options, good. At least they wont be left empty that the app is missing something. And its not like im showing all the formats in the download card. Its in a separate card, so it doesnt really ruin design
