### ISSUE TITLE
Some Fixes and Suggestions

### ISSUE THREAD

**Issue by matt873** [deniscerri/ytdlnis#148]
Though the app is almost perfect and working smoothly, below are some humble suggestions to make some things work as they should. If you found them helpful and easy to implement, please consider them:

- [x] An ability to cancel downloads from the "in queue" tab; the same cancel button for "running" downloads could be helpful in the "in queue" tab for easy cancellation.
- [x] The same circular restart button for "cancelled" downloads will be helpful in the "errored" downloads tab for an easy restart of downloads.
- [ ] Errored, and cancelled downloads notification should open their respective tab in the app.
- [x] Tapping the running downloads notification should open its respective tab showing running downloads instead of the main downloads tab.
- [x] Errored download notification disappears; it would be easy to resume it from the same resume/restart button from the notification, if it stays there, as is the case for paused downloads.
- [x] An ability to back up a list of "errored" downloads; Currently, the backup doesn't include an errored downloads list.
- [x] Optional swipe features; An ability to disable swipe gestures in settings as a download may be accidentally deleted with a swipe.

**Comment by deniscerri** [comment]
- [x]  An ability to cancel downloads from the queue tab; the same cancel button for running downloads could be helpful in the queue tab.

You can achieve this by swiping the item to the left. or click it and press delete in the bottom sheet. or click the trash button. All 3 cancel it.

- [x]  The same restart button for cancelled downloads will be helpful in the errored downloads tab for an easy restart of downloads.

You can click the errored download and click redownload in the bottom sheet. or swipe the card to the right

- [ ]  Errored, and cancelled downloads notification should open their respective tab in the app.

Noted

- [ ]  Tapping the running downloads notification should open its respective tab showing running downloads instead of the main downloads tab.

Noted

- [x]  Errored download notification disappears; it would be easy to resume it from the same resume/restart button from the notification, if it stays there, as is the case for paused downloads.

This is a design choice. The reason i didnt add them was because perhaps the user inputted a bad command, so restarting it would be pointless because it's still a bad configuration

- [ ]  An ability to back up a list of errored downloads; Currently, the backup doesn't include an errored downloads list.

Noted

- [ ]  Optional swipe features; An ability to disable swipe gestures in settings as a download may be accidentally deleted with a swipe.

In Downloads tab, they are never deleted immediately. You get a dialog box. Even if you delete an item by accident, you can restore it from the bottom snackbar. But sure ill see what i can do to make it a preference

**Comment by matt873** [comment]
1. Swiping in the "in queue" downloads tab doesn't cancel the download, instead, it deletes the download. I think the cancel button next to downloads, as is for running downloads will be helpful and will move downloads into cancel tabs from where they can be deleted.
2. The reason I said circular restart button for errored downloads is because it is easy to restart multiple downloads with ease. Suppose I have started multiple downloads and my network disconnects for some reason and now these downloads are moved to the "errored" downloads tab, then I have to tap every download and select redownload button. The restart button next to download will do the same job and will be helpful in some cases as an example mentioned above.

**Comment by deniscerri** [comment]
1. Ah i see. Well the download technically "is cancelled" meaning it wont begin to download in the future, but i guess im deleting it completely instead of moving it to the cancelled tab. Yeah that can easily be fixed

2. The reason errored downloads dont have a circular button is because if you have download logs turned on, it will show the log icon beside it so you can immediately go to its logs and see the issue. If you want to batch restart errored downloads. Simply long press an item and select the rest, or press select all in the top or invert selected then the restart button will show up. :)

**Comment by deniscerri** [comment]
![Screenshot_20230525-195747_YTDLnis](https://github.com/deniscerri/ytdlnis/assets/64997243/d69b4ed5-0100-47f7-835d-f253c2fbaea2)

**Comment by deniscerri** [comment]
> 2. Oh! I missed that. So the function is present but in a different way of doing it.

The long press actions are present also in the home screen, queued, cancelled, and download history screen

**Comment by matt873** [comment]
Thank you for creating such an excellent app. I cannot praise you enough. Based on yt-dlp, this is the best app on planet for downloading videos from any website. Thank you once more for your time and effort.

**Comment by deniscerri** [comment]
Swipe gestures are now a preference. They will be on by default to not ruin the user experience.
![image](https://github.com/deniscerri/ytdlnis/assets/64997243/b7719196-53fe-4c7c-9f0c-15907f0d5cc9)

**Comment by deniscerri** [comment]
Queued items when removed are moved to the cancelled tab as expected

**Comment by deniscerri** [comment]
Tapping on the running download notification will open the download queue screen.
Tapping on the errored notification, will open its logfile
