### ISSUE TITLE
[FEATURE REQUEST] Organize playlist files using track number or playlist index metadata

### ISSUE THREAD

**Issue by Wa1t5** [deniscerri/ytdlnis#272]
**Is your feature request available in yt-dlp? Please describe.**
When I download music playlist ydlnis doens't set the correct track number metadata

**Describe the solution you'd like**
An option or example on the app or repo's README.md of how to do it

**Describe alternatives you've considered**
I already tried to do it using custom templates but I wasn't able to make it work

**Additional context**
Sort files from playlist in the right order

**Comment by deniscerri** [comment]
The reason it doesnt work is because the app is processing each item separately and they have no idea they are in a playlist.

Possible fixes
1. Enable command as preferred download type. The app will not process any data and send you off righ in command mode. u can then use any audio/video/command and set the filename template there
2. Enable quick download. Somewhat same thing, wont process but will drop you to your fav download type
3. Use Terminal

Future solving
Since the app already saves the playlist title inside the video item. Perhaps i could also store the index inside of it and then parse the %(playlist_index)s metadata with it

then u can go off with your filename template and you're good to go. Expect this in next release

**Comment by Wa1t5** [comment]
Ok, thanks for the great app.

**Comment by deniscerri** [comment]
i did it

**Comment by Wa1t5** [comment]
> i did it

thanks, I will wait for the next release

**Comment by deniscerri** [comment]
[1.6.6.2](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.6.2-beta)
