### ISSUE TITLE
Add the dev-builds/beta/nightly apks to the releases. 

### ISSUE THREAD

**Issue by soymadip** [deniscerri/ytdlnis#28]
I was seeing that the app is under constant development and updates are pushed to dev branch almost every day (today I noticed sheduled download is implemented i guess).
So if you add the unstable/incomplete versions too to the releases(as pre-release/beta/nightly), we can try them.

**Comment by deniscerri** [comment]
The problem is that i have changed the whole app structure in the dev channel. Some features that are in the released version are not in the dev one but it has some new features.
But ill try to release one today. If you want you can join the discord and let me know what to implement since ideas are up in the air at the moment.

**Comment by soymadip** [comment]
> The problem is that i have changed the whole app structure in the dev channel. Some features that are in the released version are not in the dev one but it has some new features. But ill try to release one today. If you want you can join the discord and let me know what to implement since ideas are up in the air at the moment.

Okk
