### ISSUE TITLE
Long Playlists are limited to 100? 

### ISSUE THREAD

**Issue by shaydzmi** [deniscerri/ytdlnis#349]
When I want to download a playlist that has more than than 100 items, I can't, it shows me only the first 100.
Any idea?

**Comment by BanDroid** [comment]
> The app is supposed to get all of them. Something mightve changed in the piped api. Write some gibberish in the piped instance preference (its in updating settings). That will force the app to use yt-dlp only and it should be ok for now

i have tested, both piped and ytdlp are limited to 100 for playlist, either coyrighted music or regular content

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/f5e2f8d1-a0da-4921-8cea-cd8042ff320f)
ytdlp gives me the full playlist 
This is teh one i used
https://www.youtube.com/playlist?list=PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl

again make sure you write some gibberish since piped is broken, if you leave it empty the app will use teh default instance

**Comment by zaednasr** [comment]
btw the issue has been resolved for piped now. wait for release
