### ISSUE TITLE
[Feature Request] Please enable the "Show options for Downloading" to come up as a independent pop up window instead of opening the entire app, like Powertube or NewPipe does.

### ISSUE THREAD

**Issue by fedonr** [deniscerri/ytdlnis#4]
Powertube or NewPipe shows the download options without closing the Revanced app, as overlay and instantly starts downloading in background while with YTDLnis it closes the Revanced goes to YTDLnis and searches for the video on its homeScreen and after some delay the video shows up on YTDLnis homepage for download. Where again we have to tap to show the options and start downloading.

Sharing the SCs for Powertube and NewPipe implementation for Overlay options compares to opening the app entirely.
![Screenshot_20221207-141600](https://user-images.githubusercontent.com/120009841/206156869-8958c7ea-3300-4153-91d9-6970434ddab1.png)
![Screenshot_20221207-141633](https://user-images.githubusercontent.com/120009841/206156898-2a5277db-7a95-41ac-ad55-15cd01e14289.png)
![Screenshot_20221207-160842](https://user-images.githubusercontent.com/120009841/206157759-c84790c3-ee0d-46e1-9f5e-924c4cb09cc0.png)
![Screenshot_20221207-160849](https://user-images.githubusercontent.com/120009841/206157767-5972f83b-971d-4845-90ec-5f6167502afc.png)

**Comment by deniscerri** [comment]
I had experimented with that feature before but i found it being less useful and more complicated than just opening the app.
First you still have to wait for the app to find data about the link before showing a dialog or the card in the homepage. This is a limitation of youtubedl-android that i can't improve. 
Lists of links in a txt file and youtube playlists are thrown out of the window because you work with them in a dialog.
Home page will always be the best version. 

If you have any ideas how i could go about i could implement it, feel free. Create a discussion.

You don't have to stay in the app after it starts downloading, it can work in the background no problem. I have tried it on revanced. Even if you remove the app from recents, it will download still.

**Comment by soymadip** [comment]
> I had experimented with that feature before but i found it being less useful and more complicated than just opening the app. First you still have to wait for the app to find data about the link before showing a dialog or the card in the homepage. This is a limitation of youtubedl-android that i can't improve. Lists of links in a txt file and youtube playlists are thrown out of the window because you work with them in a dialog. Home page will always be the best version.
> 
> If you have any ideas how i could go about i could implement it, feel free. Create a discussion.
> 
> You don't have to stay in the app after it starts downloading, it can work in the background no problem. I have tried it on revanced. Even if you remove the app from recents, it will download still.

I have something in mind, powertube also uses Yt-dl. 
But it shows a dialogue too. Although as you said, because of limitation of Yt-dl/ yt-dlp it takes some time too.

**Comment by deniscerri** [comment]
I think they have their own implementation of yt-dlp instead of YouTubedl-android. I can't get a hold of the source code. Their GitHub repo is useless

**Comment by soymadip** [comment]
> I think they have their own implementation of yt-dlp instead of YouTubedl-android. I can't get a hold of the source code. Their GitHub repo is useless
Oh, i get it.
