### ISSUE TITLE
Instead of YouTube suggestion in home page, please add a url box in home page. 

### ISSUE THREAD

**Issue by Joyogirl** [deniscerri/ytdlnis#40]
Instead of YouTube suggestions in home page please add and URL box there. Because YouTube results are kinda useless and confusing while yt-dlp can download from more sites other than YouTube. Like i mainly use to download Facebook and tik tok videos. For me YouTube suggestions are useless there.
And besides YouTube results cause app loading time increase. 

In homepage, a url bar/box where we can put url will be better(for most people) and the app has no  instructions where to put url. I suddenly found out about the search icon which says 'search from YouTube'!?

But the the rest of the app is good 😊, please fix/change the home page .

**Comment by deniscerri** [comment]
You can put urls in the search bar too, but i have taken your advice and will put the search bar as expanded on the screen so that people won't get confused in the future

Like this i guess:

![image](https://user-images.githubusercontent.com/64997243/223832184-49129b06-ffa9-4559-b2d9-e9b2a4572bbc.png)

**Comment by Joyogirl** [comment]
> You can put urls in the search bar too, but i have taken your advice and will put the search bar as expanded on the screen so that people won't get confused in the future
> 
> Like this i guess:
> 
> ![image](https://user-images.githubusercontent.com/64997243/223832184-49129b06-ffa9-4559-b2d9-e9b2a4572bbc.png)

Thanks a lot sir.
