### ISSUE TITLE
Add option  'check for updates' for Yt-dlp 

### ISSUE THREAD

**Issue by Joyogirl** [deniscerri/ytdlnis#46]
Is it possible to add ytdlp's update check? 
If its possible please add it🙏
I have a concept:- 
Maybe two options under 'check for updates' option:- 
1. For app update [on/off button]
2. For Yt-dlp update [on/off button]

**Comment by deniscerri** [comment]
Checking for yt-dlp update every time you open the app could be heavy and slow down the startup since its not as simple as checking for app update. You just have to go and try to update yt-dlp and then see if you have a new version or not.

Just try manually updating when you face issues
![image](https://user-images.githubusercontent.com/64997243/224783427-41a6d7bc-46e2-48d9-8907-dbcab6e4ade0.png)

Ill do some testing and see how it performs with a boot up check and get back at you.

**Comment by soymadip** [comment]
@Joyogirl join discord, it's easier to interact there
