### ISSUE TITLE
Adding Progess While Extracting Audio [FEATURE REQUEST]

### ISSUE THREAD

**Issue by KarunaTG** [deniscerri/ytdlnis#471]
Problem : 
While Downloading Long Length (2hour+) Audio / Podcasts From YouTube it gets stuck on Extracting Audio or takes several hours 

Solution:
Adding a Progess bar when ytdlnis Extracting audio from video like it shows while downloading 

It'll help to know if the extraction is stuck and will help to know approximate time of extraction 

I hope you get my point

**Comment by zaednasr** [comment]
I understand your point but there is nothing the app can do. All the app does is read out the progress and shows it in the screen. So you would need to create this issue in the [yt-dlp repository](https://github.com/yt-dlp/yt-dlp) because they are the ones who develop the downloader component.
Go to the download history screen, tap on your downloaded audio and tap the command chip. Copy that and show it to them as reference for the command used, in case they want to experiment with it. 

If they respond, let me know what they say.
