### ISSUE TITLE
[BUG] App "successfully" downloads nothing

### ISSUE THREAD

**Issue by Gooberpatrol66** [deniscerri/ytdlnis#552]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
I'm trying to download this channel https://www.youtube.com/@KaneB
App speeds through all the videos saying they're "downloaded" but no files appear for them

**To Reproduce**
Download all for https://www.youtube.com/@KaneB

**Expected behavior**
Actual downloads

**Screenshots / Video Recording**
If applicable, add them to help explain your problem.

**(please complete the following information):**
 - Android Version: lineageos 19
 - App Version: 2024.08.21.232751
 - Other Device Information: nord n200

**Additional context**

**Comment by zaednasr** [comment]
I can reproduce it. I'll let you know when i fixed it

**Comment by zaednasr** [comment]
It seems youtube channel links dont provide playlist indexes, and since the app uses indexes to download items from the playlist, it skips. 
A workaround at the time being is to go to general settings and toggle "Use item url instead of playlist url". 
It will work but if you care about playlist metadata, it wont be added

**Comment by zaednasr** [comment]
Follow this issue i created for the channel url issue:
When closed, ill do the necessary changes in the app to fix this
[https://github.com/yt-dlp/yt-dlp/issues/10827](https://github.com/yt-dlp/yt-dlp/issues/10827)
