### ISSUE TITLE
[BUG] file name too long error

### ISSUE THREAD

**Issue by KamrulShahed** [deniscerri/ytdlnis#557]
I am getting file name too long error in 50 percent of my Facebook downloads. Previously i used .100B at the end of title of file name template and it worked but now i am getting that error again in the latest version. Maybe it stopped following the 100B rule. 

Android version: 12
App version: 1.7.9

**Comment by teddysulaimanGL** [comment]
[Q: Why did I still get the 'File name too long' error even if the app already passed the trim filenames command every time?
 A: It's because trim filenames don't work as it should if some metadata contains full stops (.) and/or non-Roman characters (Cyrillic, Devanagari, Hebrew, Arabic, etc.) The workaround for this is to enable restrict filenames to restrict the entire filename or use %(metadata_field)#S to only restrict certain metadata fields like title. Or if you want to keep these non-Roman characters to the filename, you can manually set the number of characters the app should use instead by using this following template: %(metadata_field).100B. Feel free to replace the "100" to any number you want as long as it's less than 200](https://t.me/ytdlnis/36055/76756)

Have you modified the default filename again, then?

**Comment by KamrulShahed** [comment]
Strange part is, it gives error file name too long for a file but trying again downloading the same file works sometimes. Although Not for all files.

I am not finding any file that gives this error right now. So cant check. I will inform here when i find one.

**Comment by zaednasr** [comment]
@KamrulShahed look at your filename template
use something like 
%(uploader).30B - %(title).170B

the .30B notes that the uploader is 30 bytes long max, if its longer it will be cut.
If it ends with s, then it will take the full text and it could be too long for android to handle.
